version: '3.7'

services:
  traefik:
    image: traefik:v2.0
    container_name: "${APP_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./${PROJECT_FOLDER}:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${HOST}`) && PathPrefix(`/`)"
#      - "traefik.http.routers.nginx.middlewares=portainer-prefix"
#      - "traefik.http.middlewares.portainer-prefix.stripprefix.prefixes=/"
#      - "traefik.http.middlewares.portainer-prefix.stripprefix.forceslash=false"

  mysql:
    image: mariadb:10.3
    container_name: mysql
    volumes:
      - ./.database:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  memcached:
    image: memcached:1.6
    container_name: memcached
    depends_on:
      - php

  php:
    image: wodby/drupal-php:7.4-dev-4.37.5
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ## Redirect mails to local service
      PHP_SENDMAIL_PATH: ${PHP_SENDMAIL_PATH-/usr/sbin/sendmail -t -i -S mailhog:1025}
      ## FPM Config.
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT-512M}
      PHP_MAX_INPUT_VARS: 15000
      PHP_MAX_INPUT_TIME: -1
      ## XDebug
      PHP_XDEBUG: 1
      PHP_XDEBUG_CLIENT_HOST: "172.17.0.1"
      PHP_XDEBUG_MODE: "develop,debug"
      PHP_XDEBUG_START_WITH_REQUEST: "yes"
      PHP_IDE_CONFIG: "serverName=randomizr"
      PHP_XDEBUG_LOG_LEVEL: "0"
    volumes:
      - ./${PROJECT_FOLDER}:/var/www/html

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog-${APP_NAME}.rule=Host(`mailhog.pharminno.docker.localhost`)
      - traefik.http.routers.mailhog-${APP_NAME}.service=mailhog-pharminno@docker
      - traefik.http.services.mailhog-${APP_NAME}.loadbalancer.server.port=8025
